// <auto-generated />
using System;
using C10.MasterData.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace C10.MasterData.Migrations
{
    [DbContext(typeof(MasterDataDbContext))]
    partial class MasterDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_BenhTat.DM_BenhTat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("BT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("BT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_BENH_TAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_CapToaXu.DM_CapToaXu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CTX_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("CTX_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("CTX_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_CAP_TOA_XU");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_DanToc.DM_DanToc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("DT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("DT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("DT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_DAN_TOC");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_DoTuoi.DM_DoTuoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int?>("DTU_Den_Tuoi")
                        .HasMaxLength(10)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DTU_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("DTU_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("DTU_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("DTU_Tu_Tuoi")
                        .HasMaxLength(10)
                        .HasColumnType("NUMBER(10)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_DO_TUOI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_DuocDacXa.DM_DuocDacXa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("DDX_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("DDX_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("DDX_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_DUOC_DAC_XA");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_GhiChuRieng.DM_GhiChuRieng", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("GCR_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("GCR_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("GCR_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_GHI_CHU_RIENG");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_GioiTinh.DM_GioiTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("GT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("GT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("GT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_GIOI_TINH");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_HinhPhatBoSung.DM_HinhPhatBoSung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("HPBS_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("HPBS_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("HPBS_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_HINH_PHAT_BO_SUNG");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_HinhThucChon.DM_HinhThucChon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("HTC_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("HTC_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("HTC_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_HINH_THUC_CHON");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_HinhThucKhenThuong.DM_HinhThucKhenThuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("HTKT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("HTKT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("HTKT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_HINH_THUC_KHEN_THUONG");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_HinhThucKyLuat.DM_HinhThucKyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("HTKL_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("HTKL_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("HTKL_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_HINH_THUC_KY_LUAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_HocVan.DM_HocVan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("HV_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("HV_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("HV_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_HOC_VAN");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_KyXepLoaiCaiTao.DM_KyXepLoaiCaiTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("KXLCT_FromDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("KXLCT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("KXLCT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<DateTime?>("KXLCT_ToDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("KXLCT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("KXLCT_Year")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_KY_XEP_LOAI_CAI_TAO");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LoaiPhamNhan.DM_LoaiPhamNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LPN_Ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("LPN_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("LPN_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LOAI_PHAM_NHAN");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LoaiPhanLoai.DM_LoaiPhanLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LPL_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LPL_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("LPL_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LOAI_PHAN_LOAI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LoaiQDTDC.DM_LoaiQDTDC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LQDTDC_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LQDTDC_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("LQDTDC_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LOAI_QUYET_DINH_TAM_DINH_CHI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LoaiQuyetDinhGiamGiu.DM_LoaiQuyetDinhGiamGiu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LQDGG_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LQDGG_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("LQDGG_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LOAI_QUYET_DINH_GIAM_GIU");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LoaiQuyetDinhTrichXuat.DM_LoaiQuyetDinhTrichXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LQDTX_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LQDTX_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("LQDTX_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LOAI_QUYET_DINH_TRICH_XUAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LoaiTangGiamHinhPhat.DM_LoaiTangGiamHinhPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LTGHP_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LTGHP_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("LTGHP_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LOAI_TANG_GIAM_HINH_PHAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LyDoAnGiam.DM_LyDoAnGiam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LDAG_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LDAG_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("LDAG_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LY_DO_AN_GIAM");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LyDoGiamRPN.DM_LyDoGiamRPN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LDRGPN_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LDRGPN_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("LDRGPN_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LY_DO_RIENG_GIAM_PHAM_NHAN");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LyDoKhen.DM_LyDoKhen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LDK_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LDK_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("LDK_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LY_DO_KHEN");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LyDoKhongXetGiam.DM_LyDoKhongXetGiam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LDKXG_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LDKXG_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("LDKXG_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LY_DO_KHONG_XET_GIAM");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LyDoKyLuat.DM_LyDoKyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LDKL_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LDKL_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("LDKL_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LY_DO_KY_LUAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LyDoTamDinhChi.DM_LyDoTamDinhChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LDTDC_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LDTDC_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("LDTDC_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LY_DO_TAM_DINH_CHI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_LyDoTrichXuat.DM_LyDoTrichXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LDTX_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("LDTX_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("LDTX_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("DM_LY_DO_TRICH_XUAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_MaPhanLoai.DM_MaPhanLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("MPL_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("MPL_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("MPL_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_MA_PHAN_LOAI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_MucAnPhat.DM_MucAnPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int?>("MAP_Den_Muc_An")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MAP_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("MAP_Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("MAP_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("MAP_Tu_Muc_An")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_MUC_AN_PHAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_NgheNghiep.DM_NgheNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NN_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("NN_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("NN_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_NGHE_NGHIEP");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_QuanHeVoiPN.DM_QuanHeVoiPN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("QHVPN_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("QHVPN_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("QHVPN_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_QUAN_HE_VOI_PHAM_NHAN");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_QuocTich.DM_QuocTich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("QT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("QT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("QT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_QUOC_TICH");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_SinhConTheoMeVaoTrai.DM_SinhConTheoMeVaoTrai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("SCTMVT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("SCTMVT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("SCTMVT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_SINH_CON_THEO_ME_VAO_TRAI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TaiPham.DM_TaiPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TP_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TP_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TP_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TAI_PHAM");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TinhTrangConTheoMeVaoTrai.DM_TinhTrangConTheoMeVaoTrai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TTCTMVT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TTCTMVT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TTCTMVT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TINH_TRANG_CON_THEO_ME_VAO_TRAI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TinhTrangSucKhoePN.DM_TinhTrangSucKhoePN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TTSKPN_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TTSKPN_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TTSKPN_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TINH_TRANG_SUC_KHOE_PHAM_NHAN");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TinhTrangTamDinhChi.DM_TinhTrangTamDinhChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TTTDC_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TTTDC_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TTTDC_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TINH_TRANG_TAM_DINH_CHI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TinhTrangTrichXuat.DM_TinhTrangTrichXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TTTX_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TTTX_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TTTX_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TINH_TRANG_TRICH_XUAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TinhTrangTron.DM_TinhTrangTron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TTT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TTT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TTT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TINH_TRANG_TRON");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_ToiDanh.DM_ToiDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TD_Can_Cu")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("TD_Chuong")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TD_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TD_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TD_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TOI_DANH");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TonGiao.DM_TonGiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TG_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TG_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("TG_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TON_GIAO");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TruongHopBat.DM_TruongHopBat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("THB_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("THB_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("THB_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TRUONG_HOP_BAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TruongHopChet.DM_TruongHopChet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("THC_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("THC_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("THC_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TRUONG_HOP_CHET");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TruongHopChuyenTrai.DM_TruongHopChuyenTrai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("THCT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("THCT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("THCT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TRUONG_HOP_CHUYEN_TRAI");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TruongHopMienHinhPhat.DM_TruongHopMienHinhPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("THMHP_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("THMHP_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("THMHP_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TRUONG_HOP_MIEN_HINH_PHAT");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TruongHopTha.DM_TruongHopTha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("THT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("THT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("THT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TRUONG_HOP_THA");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_TruongHopTron.DM_TruongHopTron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("THT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("THT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("THT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_TRUONG_HOP_TRON");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_XepLoaiCaiTao.DM_XepLoaiCaiTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("XLCT_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("XLCT_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("XLCT_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_XEP_LOAI_CAI_TAO");
                });

            modelBuilder.Entity("C10.MasterData.Domain.DanhMuc.DM_XuLyBat.DM_XuLyBat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("XLB_Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("XLB_Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("XLB_Trang_Thai")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("DM_XU_LY_BAT");
                });

            modelBuilder.Entity("C10.MasterData.DungChung.DM_DungChung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<Guid>("DanToc")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("GioiTinh")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("DM_DungChung");
                });
#pragma warning restore 612, 618
        }
    }
}
